# Generated by Django 4.2.5 on 2023-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
