# Generated by Django 4.2.5 on 2023-10-06 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_offer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_branches', to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(verbose_name='Table number')),
                ('bet', models.CharField(choices=[('a', 'Team A wins'), ('b', 'Team B wins')], max_length=1)),
                ('created', models.DateField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='organizations.branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
            },
        ),
    ]
