# Generated by Django 4.2.5 on 2023-10-06 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_bet_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='administrator',
        ),
        migrations.AddField(
            model_name='branch',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='controlled_branches', to=settings.AUTH_USER_MODEL, verbose_name='Administrator'),
        ),
        migrations.AddField(
            model_name='branch',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staff_branches', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
