# Generated by Django 4.2.5 on 2023-10-07 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_branch_administrator_branch_administrators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='action_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Action ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization', verbose_name='Organization'),
        ),
    ]
