# Generated by Django 4.2.5 on 2023-10-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_bet_action_id_alter_branch_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
