# Generated by Django 4.2.5 on 2023-10-16 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0008_bet_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='controlled_branches', to=settings.AUTH_USER_MODEL, verbose_name='Administrators'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
