# Generated by Django 4.2.5 on 2023-10-18 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_options_alter_bet_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-id'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='action_id',
        ),
        migrations.AddField(
            model_name='bet',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='organizations.offer', verbose_name='Offer'),
            preserve_default=False,
        ),
    ]
